version: "3.9"

services:
  devopsdb:
    image: devikadockhub/mydockerproject:db
    ports:
      - "1234:3306"
    networks:
      - mynetwork

  application:
    image: devikadockhub/mydockerproject:app
    ports:
      - "2222:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
